meta:
  name: trace_demo
  seed: 123
  study_version: 1
  objective_adapter: examples.simple_trace.myproj.optuna.objective:TraceObjectiveAdapter
  trial_adapter: examples.simple_trace.myproj.optuna.trial:TraceTrialAdapter
  worker_adapter: examples.simple_trace.myproj.optuna.worker:TraceWorkerAdapter
  optuna_adapter: examples.simple_trace.myproj.optuna.optuna:TraceOptunaAdapter
  prune_adapter: examples.simple_trace.myproj.optuna.prune:TracePruneAdapter
optuna:
  n_trials: 4
  n_jobs: 2
  storage_url: sqlite:///examples/simple_trace/optuna_trace.db
  sampler: tpe
  timeout_sec: 0
  out_path: examples/simple_trace/optuna_best.json
search_space:
  group:
    lr:
      range:
      - 0.0001
      - 0.01
      log: true
    batch_size:
    - 16
    - 32
    - 64
  dropout:
  - 0.0
  - 0.5
  fixed_flag: true
project:
  note: Example project for tracing hooks
